### ISSUE TITLE
Checked property

### ISSUE THREAD

**Issue by timka85** [materialr/checkbox#9]
Please, add `checked` prop to Checkbox component.

**Comment by hvolschenk** [comment]
Hiya,

I can definitely do that for you. Will see if I can get to it during the day today, just woke up :)

**Comment by hvolschenk** [comment]
I am just sorting out the CI build to fix the issues caused by https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes then I will release a new version.

**Comment by timka85** [comment]
thanks a lot!
